name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
# name-template: 'v$NEXT_PATCH_VERSION'
# tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "💥 Breaking Changes"
    labels:
      - "breaking"
change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

exclude-labels:
  - "skip-changelog"

exclude-contributors:
  - "Dr-Blank"

autolabeler:
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
    title:
      - "/feat(ure)?/i"
    body:
      - "/JIRA-[0-9]{1,4}/"
  - label: "chore"
    title:
      - "/chore/i"
