name: vaani
description: "Audiobookshelf client"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.17+8

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: 3.29.2

isar_version: &isar_version ^4.0.0-dev.13 # define the version to be used

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_list_plus: ^0.5.2
  animated_theme_switcher: ^2.0.10
  archive: ^4.0.5
  audio_service: ^0.18.15
  audio_session: ^0.1.23
  audio_video_progress_bar: ^2.0.2
  auto_scroll_text: ^0.0.7
  background_downloader: ^9.2.0
  cached_network_image: ^3.3.1
  coast: ^2.0.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.3.3
  duration_picker: ^1.2.0
  dynamic_color: ^1.7.0
  easy_stepper: ^0.8.4
  file_picker: ^10.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.2
  flutter_hooks: ^0.21.2
  flutter_settings_ui: ^3.0.1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  go_router: ^14.0.2
  hive: ^4.0.0-dev.2
  hooks_riverpod: ^2.5.1
  isar: ^4.0.0-dev.13
  isar_flutter_libs: ^4.0.0-dev.13
  json_annotation: ^4.9.0
  just_audio: ^0.9.37
  just_audio_background:
    # TODO Remove git dep when https://github.com/ryanheise/just_audio/issues/912 is closed
    git:
      url: https://github.com/Dr-Blank/just_audio
      ref: media-notification-config
      path: just_audio_background
  just_audio_media_kit: ^2.0.4
  list_wheel_scroll_view_nls: ^0.0.3
  logging: ^1.2.0
  logging_appenders: ^1.3.1
  lottie: ^3.1.0
  material_color_utilities: ^0.11.1
  material_symbols_icons: ^4.2785.1
  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any
  miniplayer:
    git:
      url: https://github.com/Dr-Blank/miniplayer.git
      ref: feat-notifier-for-percent-dismissed
  numberpicker: ^2.1.2
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.0
  permission_handler: ^11.3.1
  riverpod_annotation: ^2.3.5
  scroll_loop_auto_scroll: ^0.0.5
  sensors_plus: ^6.0.1
  share_plus: ^10.0.2
  shelfsdk:
    path: ./shelfsdk
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  vibration: ^3.1.3
dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/animations/
    - assets/sounds/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
